{
  "vulinfoid": "JVNDB-2018-007838",
  "vulinfodata": {
    "title": "libgit2 における境界外読み取りに関する脆弱性",
    "vulinfodescription": {
      "overview": "libgit2 には、境界外読み取りに関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Debian",
          "productname": "Debian GNU/Linux",
          "cpe": {
            "text": "cpe:/o:debian:debian_linux",
            "version": "2.2"
          }
        },
        {
          "name": "libgit2",
          "productname": "libgit2",
          "cpe": {
            "text": "cpe:/a:libgit2_project:libgit2",
            "version": "2.2"
          },
          "versionnumber": [
            "0.27.3 未満"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "4.3",
          "vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "6.5",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
        }
      ],
      "impactitem": {
        "description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "Debian",
          "vulinfoid": "[SECURITY] [DLA 1477-1] libgit2 security update",
          "url": "https://lists.debian.org/debian-lts-announce/2018/08/msg00024.html"
        },
        {
          "type": "vendor",
          "name": "GitHub",
          "vulinfoid": "delta: fix out-of-bounds read of delta",
          "url": "https://github.com/libgit2/libgit2/commit/9844d38bed10e9ff17174434b3421b227ae710f3"
        },
        {
          "type": "vendor",
          "name": "GitHub",
          "vulinfoid": "libgit2 v0.27.3",
          "url": "https://github.com/libgit2/libgit2/releases/tag/v0.27.3"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2018-10888",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-10888"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2018-10888",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-10888"
        },
        {
          "type": "advisory",
          "name": "関連文書",
          "vulinfoid": "Bug 1598024",
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1598024"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-125",
          "url": "https://cwe.mitre.org/data/definitions/125.html",
          "title": "境界外読み取り"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2018-09-28T12:30:24+09:00",
          "description": "[2018年09月28日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2018-09-28T12:30:24+09:00",
    "datelastupdated": "2018-09-28T12:30:24+09:00",
    "datepublic": "2018-07-09T00:00:00+09:00"
  }
}
