{
	"vulinfoid": "JVNDB-2019-014470",
	"vulinfodata": {
		"title": "Python におけるリソースの枯渇に関する脆弱性",
		"vulinfodescription": {
			"overview": "Python には、リソースの枯渇に関する脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "Python Software Foundation",
					"productname": "Python",
					"cpe": {
						"text": "cpe:/a:python:python",
						"version": "2.2"
					},
					"versionnumber": [
						"3.7.2 まで"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "2.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "5",
					"vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
				},
				{
					"version": "3.0",
					"severity": {
						"text": "High",
						"type": "Base"
					},
					"base": "7.5",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"impactitem": {
				"description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "cpython/Lib/zipfile.py",
					"url": "https://github.com/python/cpython/blob/master/Lib/zipfile.py"
				},
				{
					"type": "vendor",
					"name": "Python",
					"vulinfoid": "Latest News",
					"url": "https://www.python.org/blogs/"
				},
				{
					"type": "vendor",
					"name": "Python bug tracker",
					"vulinfoid": "課題36462",
					"url": "https://bugs.python.org/issue36462"
				},
				{
					"type": "vendor",
					"name": "Python bug tracker",
					"vulinfoid": "課題36260",
					"url": "https://bugs.python.org/issue36260"
				},
				{
					"type": "vendor",
					"name": "Python Security",
					"vulinfoid": "Archives and Zip Bomb",
					"url": "https://python-security.readthedocs.io/security.html#archives-and-zip-bomb"
				},
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2019-9674",
					"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-9674"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2019-9674",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-9674"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-400",
					"url": "https://cwe.mitre.org/data/definitions/400.html",
					"title": "リソースの枯渇"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2020-02-20T12:23:48+09:00",
					"description": "[2020年02月20日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2020-02-20T12:23:48+09:00",
		"datelastupdated": "2020-02-20T12:23:48+09:00",
		"datepublic": "2019-03-11T00:00:00+09:00"
	}
}
