{
  "vulinfoid": "JVNDB-2020-005117",
  "vulinfodata": {
    "title": "OpenStack Keystone における重要なデータの暗号化の欠如に関する脆弱性",
    "vulinfodescription": {
      "overview": "OpenStack Keystone には、重要なデータの暗号化の欠如に関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "OpenStack",
          "productname": "Openstack Keystone",
          "cpe": {
            "text": "cpe:/a:openstack:keystone",
            "version": "2.2"
          },
          "versionnumber": [
            "15.0.1 未満",
            "16.0.0"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "5.5",
          "vector": "AV:N/AC:L/Au:S/C:P/I:P/A:N"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "5.4",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:N"
        }
      ],
      "impactitem": {
        "description": "情報を取得される、および情報を改ざんされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "Launchpad",
          "vulinfoid": "[OSSA-2020-003] Keystone doesn't check signature TTL of the EC2 credential auth method (CVE-2020-12692)",
          "url": "https://bugs.launchpad.net/keystone/+bug/1872737"
        },
        {
          "type": "vendor",
          "name": "OpenStack Security Advisories",
          "vulinfoid": "OSSA-2020-003",
          "url": "https://security.openstack.org/ossa/OSSA-2020-003.html"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2020-12692",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-12692"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2020-12692",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-12692"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-311",
          "url": "https://cwe.mitre.org/data/definitions/311.html",
          "title": "重要なデータの暗号化の欠如"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2020-06-08T14:26:20+09:00",
          "description": "[2020年06月08日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2020-06-08T14:26:20+09:00",
    "datelastupdated": "2020-06-08T14:26:20+09:00",
    "datepublic": "2020-05-06T00:00:00+09:00"
  }
}
