{
  "vulinfoid": "JVNDB-2020-014035",
  "vulinfodata": {
    "title": "OAuthenticator における不正な認証に関する脆弱性",
    "vulinfodescription": {
      "overview": "OAuthenticator には、不正な認証に関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Project Jupyter",
          "productname": "oauthenticator",
          "cpe": {
            "text": "cpe:/a:jupyter:oauthenticator",
            "version": "2.2"
          },
          "versionnumber": [
            "0.12.0 以上 0.12.2 未満"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Low",
            "type": "Base"
          },
          "base": "3.5",
          "vector": "AV:N/AC:M/Au:S/C:P/I:N/A:N"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "6.3",
          "vector": "CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:C/C:H/I:N/A:N"
        }
      ],
      "impactitem": {
        "description": "情報を取得される可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "GitHub",
          "vulinfoid": "Changes in oauthenticator 0.12.2 - 2020-11-30",
          "url": "https://github.com/jupyterhub/oauthenticator/blob/master/docs/source/changelog.md#0122---2020-11-30"
        },
        {
          "type": "vendor",
          "name": "GitHub",
          "vulinfoid": "Merge pull request from GHSA-384w-5v3f-q499",
          "url": "https://github.com/jupyterhub/oauthenticator/commit/a4aac191c16cf6281f3d346615aefa75702b02d7"
        },
        {
          "type": "vendor",
          "name": "GitHub",
          "vulinfoid": "Base class whitelist configuration ignored - any authenticated user get access",
          "url": "https://github.com/jupyterhub/oauthenticator/security/advisories/GHSA-384w-5v3f-q499"
        },
        {
          "type": "vendor",
          "name": "Project Jupyter",
          "vulinfoid": "Add or remove users from the Hub",
          "url": "https://jupyterhub.readthedocs.io/en/1.2.2/getting-started/authenticators-users-basics.html#add-or-remove-users-from-the-hub"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2020-26250",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-26250"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2020-26250",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-26250"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-863",
          "url": "https://cwe.mitre.org/data/definitions/863.html",
          "title": "不正な認証"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2021-07-20T16:56:38+09:00",
          "description": "[2021年07月20日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2021-07-20T16:56:38+09:00",
    "datelastupdated": "2021-07-20T16:56:38+09:00",
    "datepublic": "2020-11-30T00:00:00+09:00"
  }
}
