{
  "vulinfoid": "JVNDB-2020-015598",
  "vulinfodata": {
    "title": "X.Org Server におけるバッファエラーの脆弱性",
    "vulinfodescription": {
      "overview": "X.Org Server には、バッファエラーの脆弱性が存在します。 "
    },
    "affected": {
      "affecteditem": [
        {
          "name": "X.Org Foundation",
          "productname": "X.Org X Server",
          "cpe": {
            "text": "cpe:/a:x.org:x_server",
            "version": "2.2"
          },
          "versionnumber": [
            "1.20.10 未満"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "6.1",
          "vector": "AV:L/AC:L/Au:N/C:P/I:P/A:C"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "High",
            "type": "Base"
          },
          "base": "7.8",
          "vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
      "impactitem": {
        "description": "情報を取得される、情報を改ざんされる、およびサービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "X.Org Security Advisory",
          "vulinfoid": "X.Org server security advisory: December 1, 2020",
          "url": "https://lists.x.org/archives/xorg-announce/2020-December/003066.html"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2020-14360",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14360"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2020-14360",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-14360"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-119",
          "url": "https://jvndb.jvn.jp/ja/cwe/CWE-119.html",
          "title": "バッファエラー"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2021-10-06T13:47:18+09:00",
          "description": "[2021年10月06日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2021-10-06T13:47:18+09:00",
    "datelastupdated": "2021-10-06T13:47:18+09:00",
    "datepublic": "2020-12-01T00:00:00+09:00"
  }
}
