{
  "vulinfoid": "JVNDB-2020-006834",
  "vulinfodata": {
    "title": "Pydio Cells Enterprise OVF における権限管理に関する脆弱性",
    "vulinfodescription": {
      "overview": "Pydio Cells Enterprise OVF には、権限管理に関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Pydio",
          "productname": "Cells",
          "cpe": {
            "text": "cpe:/a:pydio:cells",
            "version": "2.2"
          },
          "versionnumber": [
            "Enterprise OVF 2.0.4 およびそれ以前"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "6.9",
          "vector": "AV:L/AC:M/Au:N/C:C/I:C/A:C"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "High",
            "type": "Base"
          },
          "base": "7",
          "vector": "CVSS:3.0/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
      "impactitem": {
        "description": "情報を取得される、情報を改ざんされる、およびサービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダ情報および参考情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "Pydio",
          "vulinfoid": "Top Page",
          "url": "https://pydio.com/en"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2020-12850",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-12850"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2020-12850",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-12850"
        },
        {
          "type": "advisory",
          "name": "関連文書",
          "vulinfoid": "Pydio Cells 2.0.4 Multiple Vulnerabilities",
          "url": "https://www.coresecurity.com/core-labs/advisories/pydio-cells-204-multiple-vulnerabilities"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-269",
          "url": "https://cwe.mitre.org/data/definitions/269.html",
          "title": "不適切な権限管理"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2020-07-20T11:55:23+09:00",
          "description": "[2020年07月20日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2020-07-20T11:55:23+09:00",
    "datelastupdated": "2020-07-20T11:55:23+09:00",
    "datepublic": "2020-05-28T00:00:00+09:00"
  }
}
