{
  "vulinfoid": "JVNDB-2020-001543",
  "vulinfodata": {
    "title": "Python における入力確認に関する脆弱性",
    "vulinfodescription": {
      "overview": "Python (CPython) には、入力確認に関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Python Software Foundation",
          "productname": "Python",
          "cpe": {
            "text": "cpe:/a:python:python",
            "version": "2.2"
          },
          "versionnumber": [
            "3.6 から 3.6.10",
            "3.7 から 3.7.6",
            "3.8 から 3.8.1"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "4.3",
          "vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "5.5",
          "vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N"
        }
      ],
      "impactitem": {
        "description": "情報を改ざんされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "Python bug tracker",
          "vulinfoid": "issue39401",
          "url": "https://bugs.python.org/issue39401"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2020-8315",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8315"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2020-8315",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-8315"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-20",
          "url": "https://jvndb.jvn.jp/ja/cwe/CWE-20.html",
          "title": "不適切な入力確認"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2020-02-14T10:31:48+09:00",
          "description": "[2020年02月14日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2020-02-14T10:31:48+09:00",
    "datelastupdated": "2020-02-14T10:31:48+09:00",
    "datepublic": "2020-01-31T00:00:00+09:00"
  }
}
