{
  "vulinfoid": "JVNDB-2022-006676",
  "vulinfodata": {
    "title": "Python Software Foundation の Python 他複数ベンダの製品における信頼できない検索パスに関する脆弱性",
    "vulinfodescription": {
      "overview": "Python Software Foundation の Python 他複数ベンダの製品には、信頼できない検索パスに関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "NetApp",
          "productname": "Active IQ Unified Manager",
          "cpe": {
            "text": "cpe:/a:netapp:active_iq_unified_manager",
            "version": "2.2"
          }
        },
        {
          "name": "NetApp",
          "productname": "ONTAP Select Deploy administration utility",
          "cpe": {
            "text": "cpe:/a:netapp:ontap_select_deploy_administration_utility",
            "version": "2.2"
          }
        },
        {
          "name": "Python Software Foundation",
          "productname": "Python",
          "cpe": {
            "text": "cpe:/a:python:python",
            "version": "2.2"
          },
          "versionnumber": [
            "3.10.0 から 3.10.2",
            "3.11.0",
            "3.7.12 およびそれ以前",
            "3.8.0 から 3.8.12",
            "3.9.0 から 3.9.10"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "4.4",
          "vector": "AV:L/AC:M/Au:N/C:P/I:P/A:P"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "High",
            "type": "Base"
          },
          "base": "7",
          "vector": "CVSS:3.0/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
      "impactitem": {
        "description": "情報を取得される、情報を改ざんされる、およびサービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "参考情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2022-26488",
          "url": "https://www.cve.org/CVERecord?id=CVE-2022-26488"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2022-26488",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-26488"
        },
        {
          "type": "advisory",
          "name": "関連文書",
          "vulinfoid": "mail.python.org (657Z4XULWZNIY5FRP3OWXHYKUSIH6DMN)",
          "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/657Z4XULWZNIY5FRP3OWXHYKUSIH6DMN/"
        },
        {
          "type": "advisory",
          "name": "関連文書",
          "vulinfoid": "security.netapp.com (ntap-20220419-0005)",
          "url": "https://security.netapp.com/advisory/ntap-20220419-0005/"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-426",
          "url": "https://cwe.mitre.org/data/definitions/426.html",
          "title": "信頼できない検索パス"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2023-07-07T17:26:24+09:00",
          "description": "[2023年07月07日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2023-07-07T17:26:24+09:00",
    "datelastupdated": "2023-07-07T17:26:24+09:00",
    "datepublic": "2022-03-10T00:00:00+09:00"
  }
}
