{
	"vulinfoid": "JVNDB-2022-014765",
	"vulinfodata": {
		"title": "otfcc project の otfcc における境界外読み取りに関する脆弱性",
		"vulinfodescription": {
			"overview": "otfcc project の otfcc には、境界外読み取りに関する脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "otfcc project",
					"productname": "otfcc",
					"cpe": {
						"text": "cpe:/a:otfcc_project:otfcc",
						"version": "2.2"
					},
					"versionnumber": [
						"0.10.4"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "3.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "6.5",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
				}
			],
			"impactitem": {
				"description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "参考情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2022-35477",
					"url": "https://www.cve.org/CVERecord?id=CVE-2022-35477"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2022-35477",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-35477"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "cvjark.github.io (CVE-2022-33047)",
					"url": "https://cvjark.github.io/2022/07/06/CVE-2022-33047/"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-125",
					"url": "https://cwe.mitre.org/data/definitions/125.html",
					"title": "境界外読み取り"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2023-09-21T17:09:20+09:00",
					"description": "[2023年09月21日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2023-09-21T17:09:20+09:00",
		"datelastupdated": "2023-09-21T17:09:20+09:00",
		"datepublic": "2022-08-16T00:00:00+09:00"
	}
}
