{
	"vulinfoid": "JVNDB-2022-024867",
	"vulinfodata": {
		"title": "vinitkumar の Python 用 json2xml における例外的な状態のチェックに関する脆弱性",
		"vulinfodescription": {
			"overview": "vinitkumar の Python 用 json2xml には、例外的な状態のチェックに関する脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "vinitkumar",
					"productname": "json2xml",
					"cpe": {
						"text": "cpe:/a:vinitkumar:json2xml",
						"version": "2.2"
					},
					"versionnumber": [
						"3.12.0 およびそれ以前"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "3.0",
					"severity": {
						"text": "High",
						"type": "Base"
					},
					"base": "7.5",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"impactitem": {
				"description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダアドバイザリまたはパッチ情報が公開されています。参考情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2022-25024",
					"url": "https://www.cve.org/CVERecord?id=CVE-2022-25024"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2022-25024",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-25024"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "github.com (files)",
					"url": "https://github.com/vinitkumar/json2xml/pull/107/files"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "packaging.python.org (analyzing-pypi-package-downloads)",
					"url": "https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "github.com (issues/106)",
					"url": "https://github.com/vinitkumar/json2xml/issues/106"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "github.com (pull/107)",
					"url": "https://github.com/vinitkumar/json2xml/pull/107"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-754",
					"url": "https://cwe.mitre.org/data/definitions/754.html",
					"title": "例外的な状態における不適切なチェック"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2024-01-23T10:59:25+09:00",
					"description": "[2024年01月23日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2024-01-23T10:59:25+09:00",
		"datelastupdated": "2024-01-23T10:59:25+09:00",
		"datepublic": "2022-02-14T00:00:00+09:00"
	}
}
