{
	"vulinfoid": "JVNDB-2022-004881",
	"vulinfodata": {
		"title": "Tensorflow における例外的な状態のチェックに関する脆弱性",
		"vulinfodescription": {
			"overview": "Tensorflow には、例外的な状態のチェックに関する脆弱性が存在します。 "
		},
		"affected": {
			"affecteditem": [
				{
					"name": "Google",
					"productname": "Google TensorFlow",
					"cpe": {
						"text": "cpe:/a:google:tensorflow",
						"version": "2.2"
					},
					"versionnumber": [
						"2.5.3 未満",
						"2.6.3 未満",
						"2.7.1 未満"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "2.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "4",
					"vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P"
				},
				{
					"version": "3.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "6.5",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"impactitem": {
				"description": "サービス運用妨害 (DoS) 状態にされる可能性があります。 "
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。 "
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "Fix check-fail when bincount ops are passed invalid values.",
					"url": "https://github.com/tensorflow/tensorflow/commit/7019ce4f68925fd01cdafde26f8d8c938f47e6f9"
				},
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "Assertion failure based denial of service via faulty bin count operations",
					"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f2vv-v9cg-qhh7"
				},
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "tensorflow/tensorflow/core/kernels/bincount_op.cc",
					"url": "https://github.com/tensorflow/tensorflow/blob/5100e359aef5c8021f2e71c7b986420b85ce7b3d/tensorflow/core/kernels/bincount_op.cc"
				},
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2022-21737",
					"url": "https://www.cve.org/CVERecord?id=CVE-2022-21737"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2022-21737",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-21737"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-754",
					"url": "https://cwe.mitre.org/data/definitions/754.html",
					"title": "例外的な状態における不適切なチェック"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2023-05-10T13:56:31+09:00",
					"description": "[2023年05月10日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2023-05-10T13:56:51+09:00",
		"datelastupdated": "2023-05-10T13:56:51+09:00",
		"datepublic": "2022-02-03T00:00:00+09:00"
	}
}
