{
  "vulinfoid": "JVNDB-2021-001974",
  "vulinfodata": {
    "title": "IBM Cognos Analytics における XML 外部エンティティの脆弱性",
    "vulinfodescription": {
      "overview": "IBM Cognos Analytics には、XML 外部エンティティの脆弱性が存在します。  ベンダは、本脆弱性を IBM X-Force ID: 176607 として公開しています。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "IBM",
          "productname": "IBM Cognos Analytics",
          "cpe": {
            "text": "cpe:/a:ibm:cognos_analytics",
            "version": "2.2"
          },
          "versionnumber": [
            "11.0",
            "11.1"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "6.4",
          "vector": "AV:N/AC:L/Au:N/C:P/I:N/A:P"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "High",
            "type": "Base"
          },
          "base": "8.2",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:L"
        }
      ],
      "impactitem": {
        "description": "情報を取得される、およびサービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "IBM Support Document",
          "vulinfoid": "6451705",
          "url": "https://www.ibm.com/support/pages/node/6451705"
        },
        {
          "type": "vendor",
          "name": "IBM X-Force Exchange",
          "vulinfoid": "ibm-cognos-cve20204300-xxe (176607)",
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/176607"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2020-4300",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-4300"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2020-4300",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-4300"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-611",
          "url": "https://cwe.mitre.org/data/definitions/611.html",
          "title": "XML 外部エンティティ参照の不適切な制限"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2021-07-06T17:12:18+09:00",
          "description": "[2021年07月06日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2021-07-06T17:12:18+09:00",
    "datelastupdated": "2021-07-06T17:12:18+09:00",
    "datepublic": "2021-05-28T00:00:00+09:00"
  }
}
