{
	"vulinfoid": "JVNDB-2021-009145",
	"vulinfodata": {
		"title": "Linux Kernel における NULL ポインタデリファレンスに関する脆弱性",
		"vulinfodescription": {
			"overview": "Linux Kernel には、NULL ポインタデリファレンスに関する脆弱性が存在します。 "
		},
		"affected": {
			"affecteditem": [
				{
					"name": "Linux",
					"productname": "Linux Kernel",
					"cpe": {
						"text": "cpe:/o:linux:linux_kernel",
						"version": "2.2"
					},
					"versionnumber": [
						"5.12.10 未満"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "2.0",
					"severity": {
						"text": "Low",
						"type": "Base"
					},
					"base": "2.1",
					"vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
				},
				{
					"version": "3.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "5.5",
					"vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"impactitem": {
				"description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "vendor",
					"name": "ChangeLog",
					"vulinfoid": "ChangeLog-5.12.10",
					"url": "https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.12.10"
				},
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "nfc: fix NULL ptr dereference in llcp_sock_getname() after failed connect",
					"url": "https://github.com/torvalds/linux/commit/4ac06a1e013cf5fdd963317ffd3b968560f33bba"
				},
				{
					"type": "vendor",
					"name": "Linux Kernel",
					"vulinfoid": "Linux Kernel Archives",
					"url": "https://www.kernel.org"
				},
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2021-38208",
					"url": "https://www.cve.org/CVERecord?id=CVE-2021-38208"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2021-38208",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-38208"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "Bug 1992810",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1992810"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-476",
					"url": "http://cwe.mitre.org/data/definitions/476.html",
					"title": "NULL ポインタデリファレンス"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2022-04-13T15:27:47+09:00",
					"description": "[2022年04月13日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2022-04-13T15:27:47+09:00",
		"datelastupdated": "2022-04-13T15:27:47+09:00",
		"datepublic": "2021-06-10T00:00:00+09:00"
	}
}
