{
	"vulinfoid": "JVNDB-2021-006092",
	"vulinfodata": {
		"title": "Exiv2 における境界外読み取りに関する脆弱性",
		"vulinfodescription": {
			"overview": "Exiv2 には、境界外読み取りに関する脆弱性が存在します。 "
		},
		"affected": {
			"affecteditem": [
				{
					"name": "Exiv2 project",
					"productname": "Exiv2",
					"cpe": {
						"text": "cpe:/a:exiv2:exiv2",
						"version": "2.2"
					},
					"versionnumber": [
						"0.27.3 およびそれ以前"
					]
				},
				{
					"name": "Fedora Project",
					"productname": "Fedora",
					"cpe": {
						"text": "cpe:/o:fedoraproject:fedora",
						"version": "2.2"
					}
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "2.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "4.3",
					"vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
				},
				{
					"version": "3.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "6.5",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
				}
			],
			"impactitem": {
				"description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。 "
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "vendor",
					"name": "Fedora Update Notification",
					"vulinfoid": "FEDORA-2021-10d7331a31",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2XQT5F5IINTDYDAFGVGQZ7PMMLG7I5ZZ/"
				},
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "Add more bounds checks in Jp2Image::encodeJp2Header #1581",
					"url": "https://github.com/Exiv2/exiv2/pull/1581"
				},
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "Out-of-bounds read in Exiv2::Jp2Image::encodeJp2Header",
					"url": "https://github.com/Exiv2/exiv2/security/advisories/GHSA-8949-hhfh-j7rj"
				},
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2021-29470",
					"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-29470"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2021-29470",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-29470"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-125",
					"url": "https://cwe.mitre.org/data/definitions/125.html",
					"title": "境界外読み取り"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2021-12-27T11:07:53+09:00",
					"description": "[2021年12月27日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2021-12-27T11:07:53+09:00",
		"datelastupdated": "2021-12-27T11:07:53+09:00",
		"datepublic": "2021-04-23T00:00:00+09:00"
	}
}
